- src/Components/Home.js
- src/Components/Login.js
- src/Components/Nav.js
- webpack.config.js
Updated login page functionality
> Updated Login

- src/Components/Login.js
- static/index.html
- static/styles.css
> Updated Login Page

- server/app.js
- server/db/models/User.js
- src/store/auth.js
Oauth & Passport to create a Google login feature
> Created Google Login

- server/api/index.js
- server/api/routes/auth.js
- server/app.js
- server/google-auth.js
Created google-auth.js to make code cleaner
> CleanUp-Code

- src/Components/Global/Footer.js
- src/Components/Global/NotFound.js
- src/Components/User/Login.js
- src/Components/User/Register.js
- static/index.css
Updated size of login form and register form when in mobile screen size
> Updated CSS

- less/createleague.less
- server/db/models/League.js
- src/Components/League.js
- src/Forms/CreateLeague.js
- static/index.css
Mostly done, upload logo left.
> Implemented create league functionality

- server/db/models/League.js
- src/Components/Landing2.js
- src/Components/League.js
- src/Forms/CreateLeague.js
- src/store/leaguesSlice.js
User now able to upload logo and preview the logo
> Added Upload Logo function

- less/createteam.less
- src/Components/League.js
- src/Forms/CreateTeam.js
- static/index.css
> Create Team Page

- src/Components/User/Login.js
created logged in page if user logged in already
> Updated Login.js

- src/Forms/CreateLeague.js
- src/Forms/CreateTeam.js
Added Validation to create team page, user can not enter name that already exists, and also email validation
> Updated Validation

- src/Forms/RequestJoinPlayer.js
- src/Forms/RequestJoinTeam.js
Team request form done, player request form need to modify after meet up
> Updated Request Form

- less/createteam.less
- less/index.less
- less/landing3.less
- server/db/models/Mesages.js
- server/db/models/Player.js
- src/Forms/CreatePlayer.js
- static/index.css
Layout completed, need to work on the functionality.
> Updated Create Player Form

- less/userProfile.less
- src/Components/User/UserProfile.js
- src/Components/User/UserProfileAccountDetail.js
- static/index.css
Added account details functionality
> Updated User Profile

- server/api/routes/auth.js
- server/app.js
- src/Components/User/UserProfileAccountDetail.js
- src/store/auth.js
User now able to update profile
> Added Update Profile

- package-lock.json
- src/Components/User/UserProfileAccountDetail.js
- src/Forms/RequestJoinTeam.js
Added validations to account details page
> Updated Profile Page

- src/Components/User/UserProfileAccountDetail.js
> Updated User Profile Page

- less/navbar.less
- less/staff.less
- less/userProfile.less
- src/Components/Global/Staff.js
- src/Components/User/UserProfileAccountDetail.js
- static/index.css
> Updated Staff Page

- less/staff.less
- server/db/models/User.js
- src/Components/User/Login.js
- src/Components/User/UserProfileAccountDetail.js
- src/Components/User/UserProfileSecurity.js
- static/index.css
Added modal asking user to confirm change password
> Add confirmation modal

- less/createteam.less
- less/navbar.less
- less/vars.less
- src/Components/Global/Footer.js
- src/Forms/CreateTeam.js
- static/index.css
User can add invite player to the team when creating a team
> Updated  create team form

- server/passport.js
- src/Components/User/Login.js
- src/Components/User/UserProfileAccountDetail.js
> Updated Oauth

- less/staff.less
- src/App.js
- src/Components/Global/Nav.js
- src/Components/Global/Staff.js
- src/Components/Landing3.js
- src/Components/User/UserProfile.js
- src/Components/User/UserProfileAccountDetail.js
- src/Components/User/UserProfileSecurity.js
- src/store/auth.js
- static/index.css
> Updated auth slice
